#ifndef RR_SUBSCRIBER_HPP
#define RR_SUBSCRIBER_HPP

#include "rclcpp/rclcpp.hpp"
#include "rr_interfaces/msg/buffer_response.hpp"
#include <functional>
#include <list>
#include <memory>

namespace rrobot
{

/**
 * @class RrController
 * @brief coordinates subscriptions and publishing services for buffer
 * 
 * TODO: Publishing needs to be separated from this service, also a global message
 * does not seem like the best idea, messages should be generated by publishing service
 * that is coordinated by this class.
 */
class RrController : public rclcpp::Node
{
public:
  RrController() : Node("rr_buffer_controller")
  {}

  ~RrController() = default;

  /**
   * @fn init
   * @brief performs initlization, including creating the subscriber.
   */
  void init();

  /**
   * @fn set_gps
   * @brief set_gps
   * 
   * allows gps  subscriber to set current value.
   */
  void set_gps(const sensor_msgs::msg::NavSatFix);
  const sensor_msgs::msg::NavSatFix get_gps();

  /**
   * @fn set_joystick
   * @brief allows joystick subscriber to set current value.
   */
  void set_joystick(const sensor_msgs::msg::Joy);
  const sensor_msgs::msg::Joy get_joystick();

  /**
   * @fn set_batt_state
   * @brief allows battery_state subscriber to set current value.
   */
  void set_batt_state(const sensor_msgs::msg::BatteryState);
  const sensor_msgs::msg::BatteryState get_batt_state();

  /**
   * @fn set_img
   * @brief allows video stream subscriber to set current value.
   */
  void set_img(const sensor_msgs::msg::Image);

  /**
   * @fn set_imu
   * @brief allows IMU subscriber to set current value.
   */
  void set_imu(const sensor_msgs::msg::Imu);
  const sensor_msgs::msg::Imu get_imu();

  /**
   * @fn set_ranges
   * @brief allows Ultra-Sonics, radors and other distance sensor 
   * subscriber to set current value.
   */
  void set_ranges(const std::list<sensor_msgs::msg::Range>);
  const std::list<sensor_msgs::msg::Range> get_ranges();

private:  
  /**
   * @fn reset_response 
   * @brief Creates new Response and new GUID
   */
  void reset_response();

  /**
   * @fn callback
   * @brief callbacks based on timer.
   */
  void callback();

  /**
   * @fn publish
   * @brief publishes to the buffer topic.
   * 
   */
  void publish();

  rclcpp::TimerBase::SharedPtr timer_;
  rclcpp::Publisher<rr_interfaces::msg::BufferResponse>::SharedPtr publisher_;
  size_t count_ = 0;

  // // Shared variables between subscribers, and publisher.
  rr_interfaces::msg::BufferResponse::SharedPtr buffer_response_;
  std::shared_mutex mutex_; // shared mutex to allow multiple readers or one writer
};
} // namespace rrobot

#endif